# Generated by Django 3.1.6 on 2021-02-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo_Book',
            new_name='Book',
        ),
    ]
